### ISSUE TITLE
Frumos proiect

### ISSUE THREAD

**Issue by GheorgheCazacu** [calingeorgeadrian/StoreManagementSystem#1]
Ati atins toate obiectivele si chiar arata frumos.
Singura observatie ar fi legata de servicii nu are sens sa faceti toate metodele statice
aveti o singura instanta in tot jvm-ul pentru acea clasa => totul va merge ok cu getInstance().doStuff() ...
In rest este foarte frumos.
O seara frumoasa

**Comment by calingeorgeadrian** [comment]
Va multumesc.
Am rezolvat problema cu metodele statice in etapa a doua a proiectului.
